# Generated by Django 4.1 on 2022-09-02 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=100, null=True)),
                ('profile_img', models.ImageField(default='https://www.kindpng.com/picc/m/451-4517876_default-profile-hd-png-download.png', upload_to='profile')),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=10, null=True)),
                ('country', models.CharField(default='India', max_length=128, null=True)),
                ('state', models.CharField(max_length=128, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('street', models.CharField(blank=True, max_length=128)),
                ('zip_code', models.CharField(default='43701', max_length=10)),
                ('nationa_id', models.FileField(default=None, null=True, upload_to='user1/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
