# Generated by Django 4.1 on 2022-09-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='nationa_id',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='street',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='email_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
