# Generated by Django 4.1 on 2022-09-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_customerprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(default='India', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='nationa_id',
            field=models.FileField(default=None, null=True, upload_to='user1/'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phonenumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_img',
            field=models.ImageField(default='https://www.kindpng.com/picc/m/451-4517876_default-profile-hd-png-download.png', upload_to='profile'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='state',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='street',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='zip_code',
            field=models.CharField(default='43701', max_length=10),
        ),
    ]
