# Generated by Django 4.1 on 2022-09-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_customerprofile_firstname_customerprofile_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='email_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
