# Generated by Django 4.1 on 2022-09-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_customerprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='nationa_id',
            field=models.FileField(blank=True, null=True, upload_to='user1/'),
        ),
    ]
