# Generated by Django 4.1 on 2022-09-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_customerprofile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='nationa_id',
            field=models.FileField(blank=True, null=True, upload_to='user_doc'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img'),
        ),
    ]
