# Generated by Django 4.1 on 2022-09-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_customerprofile_nationa_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='hotel_img',
            field=models.ImageField(blank=True, null=True, upload_to='hotels'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='hotelname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
