# Generated by Django 4.1 on 2022-09-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_bookings_end_date_alter_bookings_hotel_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='room_des',
            new_name='room_name',
        ),
        migrations.AddField(
            model_name='bookings',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
