# Generated by Django 4.1 on 2022-09-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_rename_room_des_bookings_room_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='room_name',
            new_name='room_des',
        ),
    ]
