# Generated by Django 4.1 on 2022-09-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_customerprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phonenumber',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
