# Generated by Django 4.1 on 2022-09-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_customerprofile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='', max_length=250)),
                ('message', models.CharField(default='', max_length=1000)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.customerprofile')),
            ],
        ),
    ]
